name: CI/CD Pipeline

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (dev or prod)'
        required: false
        default: 'dev'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment || 'dev' }}
      TFVARS_FILE: envs/${{ github.event.inputs.environment || 'dev' }}/terraform.tfvars
      STATE_KEY: terraform-${{ github.event.inputs.environment || 'dev' }}.tfstate
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init & Validate
        run: |
          terraform init -backend-config="key=${STATE_KEY}"
          terraform validate

      - name: Run tests
        run: |
          echo "Running placeholder tests..."
          # Add your test commands below
          # Example: pytest tests/

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t analytics-dashboard:${{ github.sha }} ./dashboard

      - name: Tag Docker image
        run: |
          docker tag analytics-dashboard:${{ github.sha }} $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/analytics-dashboard:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/analytics-dashboard:${{ github.sha }}

      - name: Terraform Apply
        run: |
          terraform init -backend-config="key=${STATE_KEY}"
          terraform apply -auto-approve -var="dashboard_image=$AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/analytics-dashboard:${{ github.sha }}" -var-file=${TFVARS_FILE}
