name: CI/CD Pipeline

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (dev or prod)'
        required: false
        default: 'dev'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment || 'dev' }}
      TFVARS_FILE: envs/${{ github.event.inputs.environment || 'dev' }}/terraform.tfvars
      STATE_KEY: terraform-${{ github.event.inputs.environment || 'dev' }}.tfstate
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init & Validate
        run: |
          terraform init \
            -backend-config="bucket=customer-feedback-terraform-state" \
            -backend-config="key=${ENVIRONMENT}/terraform.tfstate" \
            -backend-config="region=ap-south-1" \
            -backend-config="lock_table=terraform-locks" \
            -input=false -force-copy
          terraform validate
          
          # Show current state
          echo "Current state resources:"
          terraform state list || echo "No state or unable to list state"

      - name: Run tests
        run: |
          echo "Running placeholder tests..."
          # Add your test commands below
          # Example: pytest tests/

      - name: Check, create, and import ECR repository if needed
        run: |
          echo "Checking if ECR repository exists in AWS and Terraform state..."
          if ! aws ecr describe-repositories --repository-names analytics-dashboard --region ap-south-1 >/dev/null 2>&1; then
            echo "ECR repository does not exist, creating it..."
            aws ecr create-repository --repository-name analytics-dashboard --region ap-south-1
            echo "Waiting 10 seconds for repository to become fully available..."
            sleep 10
          else
            echo "ECR repository already exists in AWS."
          fi
          # Check if ECR is in Terraform state, import if not
          if ! terraform state list -var-file=${TFVARS_FILE} | grep -q "aws_ecr_repository.dashboard"; then
            echo "ECR repository not in Terraform state, importing..."
            terraform import -var-file=${TFVARS_FILE} aws_ecr_repository.dashboard analytics-dashboard || echo "Import failed or not needed."
          else
            echo "ECR repository already in Terraform state."
          fi
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t analytics-dashboard:${{ github.sha }} ./dashboard

      - name: Tag Docker image
        run: |
          docker tag analytics-dashboard:${{ github.sha }} $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/analytics-dashboard:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/analytics-dashboard:${{ github.sha }}       

          


      - name: Terraform Plan & Apply
        run: |
          export TF_VAR_dashboard_image="$AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/analytics-dashboard:${{ github.sha }}"
          echo "Using dashboard image: $TF_VAR_dashboard_image"
          echo "dashboard_image = \"$AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/analytics-dashboard:${{ github.sha }}\"" > temp_vars.tfvars
          echo "Created temp_vars.tfvars with content:"
          cat temp_vars.tfvars
          echo "dashboard_image = \"$AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/analytics-dashboard:${{ github.sha }}\"" > terraform.auto.tfvars
          terraform plan -lock=false -input=false -var-file=${TFVARS_FILE} -var-file=temp_vars.tfvars -var="dashboard_image=$AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/analytics-dashboard:${{ github.sha }}" -out=tfplan
          terraform apply -auto-approve -input=false tfplan
