name: CI/CD Pipeline

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (dev or prod)'
        required: false
        default: 'dev'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment || 'dev' }}
      TFVARS_FILE: envs/${{ github.event.inputs.environment || 'dev' }}/terraform.tfvars
      STATE_KEY: terraform-${{ github.event.inputs.environment || 'dev' }}.tfstate
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init & Validate
        run: |
          # Clean any local state that might interfere
          rm -rf .terraform/
          
          # Initialize with proper backend config
          terraform init \
            -backend-config="bucket=customer-feedback-terraform-state" \
            -backend-config="key=${ENVIRONMENT}/terraform.tfstate" \
            -backend-config="region=ap-south-1" \
            -backend-config="dynamodb_table=terraform-locks" \
            -input=false -force-copy
          
          # Validate configuration
          terraform validate
          
          # Show current state
          echo "Current state resources:"
          terraform state list || echo "No state or unable to list state"

      - name: Run tests
        run: |
          echo "Running placeholder tests..."
          # Add your test commands below
          # Example: pytest tests/

      - name: Check and prepare ECR repository
        run: |
          # Check if ECR repository exists
          echo "Checking if ECR repository exists..."
          if ! aws ecr describe-repositories --repository-names analytics-dashboard --region ap-south-1 >/dev/null 2>&1; then
            echo "ECR repository does not exist, creating it manually..."
            aws ecr create-repository --repository-name analytics-dashboard --region ap-south-1
            # Add a delay to ensure the repository is fully created and available
            echo "Waiting 10 seconds for repository to become fully available..."
            sleep 10
          else
            echo "ECR repository already exists"
          fi
          
          # Verify that the repository is accessible
          echo "Verifying repository access..."
          aws ecr describe-repositories --repository-names analytics-dashboard --region ap-south-1
          
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t analytics-dashboard:${{ github.sha }} ./dashboard

      - name: Tag Docker image
        run: |
          docker tag analytics-dashboard:${{ github.sha }} $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/analytics-dashboard:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/analytics-dashboard:${{ github.sha }}
          
      - name: Check and force-unlock state if needed
        run: |
          # Check if state is locked and force unlock if necessary
          echo "Checking for any stale state locks..."
          terraform init \
            -backend-config="bucket=customer-feedback-terraform-state" \
            -backend-config="key=${ENVIRONMENT}/terraform.tfstate" \
            -backend-config="region=ap-south-1" \
            -backend-config="dynamodb_table=terraform-locks" \
            -input=false -force-copy
            
          # First try to detect a lock
          LOCK_ID=$(aws dynamodb get-item --table-name terraform-locks --key '{"LockID":{"S":"customer-feedback-terraform-state/'${ENVIRONMENT}'/terraform.tfstate"}}' --query "Item.LockID.S" --output text 2>/dev/null || echo "")
          
          if [ "$LOCK_ID" != "None" ] && [ "$LOCK_ID" != "null" ] && [ ! -z "$LOCK_ID" ]; then
            echo "Found a lock with ID: $LOCK_ID - attempting to force unlock..."
            LOCK_ID_VALUE=$(aws dynamodb get-item --table-name terraform-locks --key '{"LockID":{"S":"customer-feedback-terraform-state/'${ENVIRONMENT}'/terraform.tfstate"}}' --query "Item.ID.S" --output text 2>/dev/null || echo "")
            if [ ! -z "$LOCK_ID_VALUE" ]; then
              terraform force-unlock -force "$LOCK_ID_VALUE"
            else
              echo "Could not get lock ID value, manually clearing lock from DynamoDB..."
              aws dynamodb delete-item --table-name terraform-locks --key '{"LockID":{"S":"customer-feedback-terraform-state/'${ENVIRONMENT}'/terraform.tfstate"}}'
            fi
          else
            echo "No stale lock detected, continuing normally"
          fi
          
      # We need to check if the ECR repository exists in Terraform state and import it if needed
      - name: Check and import ECR repository if needed
        run: |
          echo "Checking if ECR repository exists and importing it if needed..."
          
          # First ensure we have initialized Terraform
          terraform init \
            -backend-config="bucket=customer-feedback-terraform-state" \
            -backend-config="key=${ENVIRONMENT}/terraform.tfstate" \
            -backend-config="region=ap-south-1" \
            -backend-config="dynamodb_table=terraform-locks" \
            -input=false -force-copy -reconfigure
          
          # Check if the ECR repository exists in AWS first
          echo "Verifying repository exists in AWS..."
          if ! aws ecr describe-repositories --repository-names analytics-dashboard --region ap-south-1 >/dev/null 2>&1; then
            echo "WARNING: ECR repository doesn't exist in AWS yet, will be created during apply"
            exit 0 # Exit successfully, as we'll create it during apply
          fi
          
          # Check if the repository is already in state (with variables)
          if ! terraform state list -var-file=${TFVARS_FILE} | grep -q "aws_ecr_repository.dashboard"; then
            echo "ECR repository not in Terraform state, importing it..."
            # Try to import the repository into state (with variables)
            if terraform import -var-file=${TFVARS_FILE} aws_ecr_repository.dashboard analytics-dashboard; then
              echo "Import successful"
            else 
              echo "Import failed, but repository exists. Will attempt to create during apply."
              # Generate a state conflict error report to help debug
              terraform plan -input=false -var-file=${TFVARS_FILE} -refresh-only || true
            fi
          else
            echo "ECR repository already in Terraform state"
          fi

      - name: Terraform Apply
        run: |
          # Remove any stale terraform files
          rm -rf .terraform/
          rm -f terraform.tfstate*
          
          # Always clear any potential stale locks first
          echo "Clearing any potential stale locks..."
          aws dynamodb delete-item --table-name terraform-locks --key '{"LockID":{"S":"customer-feedback-terraform-state/'${ENVIRONMENT}'/terraform.tfstate"}}' || echo "No lock to clear"
          
          # Ensure we have the latest state before proceeding
          terraform init \
            -backend-config="bucket=customer-feedback-terraform-state" \
            -backend-config="key=${ENVIRONMENT}/terraform.tfstate" \
            -backend-config="region=ap-south-1" \
            -backend-config="dynamodb_table=terraform-locks" \
            -input=false -force-copy -reconfigure
          
          # Set dashboard image in environment variable and verify it's set
          export TF_VAR_dashboard_image="$AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/analytics-dashboard:${{ github.sha }}"
          echo "Using dashboard image: $TF_VAR_dashboard_image"
          
          # Create tfvars files with the image variable explicitly set
          echo "dashboard_image = \"$AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/analytics-dashboard:${{ github.sha }}\"" > temp_vars.tfvars
          echo "Created temp_vars.tfvars with content:"
          cat temp_vars.tfvars
          
          # Generate terraform.auto.tfvars as well (automatically loaded)
          echo "dashboard_image = \"$AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/analytics-dashboard:${{ github.sha }}\"" > terraform.auto.tfvars
          
          # Run a plan with paranoid variable handling
          echo "Running plan..."
          terraform plan -lock=false -input=false -var-file=${TFVARS_FILE} -var-file=temp_vars.tfvars -var="dashboard_image=$AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/analytics-dashboard:${{ github.sha }}" -out=tfplan
          
          # Now run apply using the plan file to ensure no prompting
          echo "Running apply..."
          if terraform apply -auto-approve -input=false tfplan; then
            echo "Apply from plan file succeeded"
          else
            echo "Apply from plan failed, trying direct apply..."
            terraform apply -auto-approve -lock=false -input=false -var-file=${TFVARS_FILE} -var-file=temp_vars.tfvars -var="dashboard_image=$AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/analytics-dashboard:${{ github.sha }}"
          fi
